name: 'Hello World'
description: 'Greet someone'
inputs:
  repo-name:
    description: 'Repository name'
    required: true
  slack-url:
    description: 'The slack webhook'
    required: true
runs:
  using: "composite"
  steps:
    - run: scan.sh
      shell: bash
    - uses: MancunianSam/github-actions/.github/actions/slack-send@main
      if: failure()
      with:
        message: Secrets found in repository ${{ inputs.repo_name }}
        slack-url: ${{ inputs.slack-url }}
