# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
outputs:
  files: # id of output
    description: 'ls output'
  pwd: # id of output
    description: 'pwd output'
runs:
  using: 'docker'
  image: 'Dockerfile'
