name: TDR Tag and pre deploy
on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
    secrets:
      MANAGEMENT_ACCOUNT:
        required: true
      WORKFLOW_PAT:
        required: true

permissions:
  id-token: write
  contents: write
jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    environment: intg
    steps:
      - uses: actions/checkout@v2
      - uses: MancunianSam/github-actions/increment-version@main
        id: increment
        with:
          repo_name: tdr-${{ inputs.repo_name }}
      - uses: MancunianSam/github-actions/docker-action@main
        id: docker
      - run: |
              echo ${{ steps.increment.outputs.next_version }}
              echo ${{ steps.increment.outputs.files }}
              echo ${{ steps.increment.outputs.pwd }}
              echo ${{ steps.docker.outputs.files }}
              echo ${{ steps.docker.outputs.pwd }}