name: TDR Tag and pre deploy
on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
    secrets:
      MANAGEMENT_ACCOUNT:
        required: true
      WORKFLOW_PAT:
        required: true

permissions:
  id-token: write
  contents: write
jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    environment: intg
    steps:
      - uses: actions/checkout@v2
      - uses: MancunianSam/github-actions/.github/actions/build-docker-image@main
        id: increment
        with:
          who-to-greet: bob
