name: TDR Tag and pre deploy
on:
  workflow_call:
    inputs:
      test_command:
        required: true
        type: string
    secrets:
      MANAGEMENT_ACCOUNT:
        required: true
      SLACK_WEBHOOK:
        required: true

jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    environment: intg
    steps:
      - uses: coursier/cache-action@v6
      - uses: MancunianSam/github-actions/.github/actions/run-git-secrets@main
      - name: Configure AWS credentials from management account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.MANAGEMENT_ACCOUNT }}:role/TDRGithubActionsRoleMgmt
          aws-region: eu-west-2
          role-session-name: APIDownloadDependencies
      - run: ${{ inputs.test_command }}
